### ISSUE TITLE
[Android] TouchEffect crashes on Android API  Level 21

### ISSUE THREAD

**Issue by Amine24h** [AndreiMisiukevich/TouchEffect#57]
**Description**
The application crashes when opening a Page with TouchEffect.

**Basic Information**
Tested with Huawei P8 lite

**Code snippet**
`<yummy:PancakeView Grid.Row="4"
                                       HeightRequest="50"
                                       Margin="30"
                                       HorizontalOptions="FillAndExpand"
                                       BackgroundColor="#bc91d7"
                                       BackgroundGradientAngle="70"
                                       BackgroundGradientEndColor="#FEA23B"
                                       BackgroundGradientStartColor="#F4C657"
                                       CornerRadius="100"
                                       touch:TouchEff.NativeAnimation="True"
                                       touch:TouchEff.Command="{Binding LoginCommand}">
                        <yummy:PancakeView.Effects>
                            <touch:TouchEff />
                        </yummy:PancakeView.Effects>
                        <Label HorizontalOptions="Center"
                               VerticalOptions="Center"
                               FontAttributes="Bold"
                               FontSize="20"
                               TextColor="White"
                               Text="Se connecter" />
                    </yummy:PancakeView>`

**Stack trace**
`java.lang.NoSuchMethodError: no non-static method "Landroid/graphics/drawable/RippleDrawable;.setRadius(I)V"
     FATAL EXCEPTION: main
Process: dz.grapps.tenasec, PID: 24419
java.lang.NoSuchMethodError: no non-static method "Landroid/graphics/drawable/RippleDrawable;.setRadius(I)V"
	at crc64720bb2db43a66fe9.FragmentContainer.n_onCreateView(Native Method)
	at crc64720bb2db43a66fe9.FragmentContainer.onCreateView()
	at android.support.v4.app.Fragment.performCreateView()
	at android.support.v4.app.FragmentManagerImpl.moveToState()
	at android.support.v4.app.FragmentManagerImpl.addAddedFragments()
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether()
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute()
	at android.support.v4.app.FragmentManagerImpl.execPendingActions()
	at android.support.v4.app.FragmentManagerImpl$1.run()
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5538)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)`

**Comment by AndreiMisiukevich** [comment]
What android version does it have?

**Comment by AndreiMisiukevich** [comment]
Thanks for the report, fixed
